version: "3.8"

services: 
  rabbitmq:
    image: rabbitmq:4.0-alpine
    ports:
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 15s
      retries: 10

  webapp:
    build: ./
    restart: always
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      DEPLOYMENT_MODE: dev
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}

    volumes:
      - type: bind
        source: example_body.json
        target: /app/example_body.json
